"""Тесты PG-схемы working-таблиц, alembic 016 и порядка миграции."""

import importlib.util
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DDL_PATH = ROOT / "src" / "content_factory" / "catalog" / "sql" / "working_tables_postgres.sql"
FUNCTIONS_PATH = ROOT / "src" / "content_factory" / "catalog" / "sql" / "catalog_functions_postgres.sql"
MIG_PATH = ROOT / "migrations" / "versions" / "016_catalog_working_tables.py"
MIGRATE_SCRIPT = ROOT / "scripts" / "migrate_catalog_to_postgres.py"

# Таблицы, создаваемые ИМЕННО этой миграцией (curriculum_plan/row принадлежат 015).
EXPECTED_CREATED = {
    "profile_brief", "evidence_source", "evidence_query_cache", "skill_suggestion",
    "skill_prerequisite", "prerequisite_edge_decision", "intake_job",
    "curriculum_artifact_template", "curriculum_artifact_template_scope",
    "skill_set", "skill_set_item", "curriculum_artifact_template_proposal",
    "skill_promotion_log",
}


def _load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_ddl_creates_expected_working_tables() -> None:
    sql = DDL_PATH.read_text(encoding="utf-8")
    created = set(re.findall(r"CREATE TABLE IF NOT EXISTS catalog\.(\w+)", sql))
    assert created == EXPECTED_CREATED


def test_ddl_does_not_redefine_curriculum_plan_tables() -> None:
    """curriculum_plan/row создаёт миграция 015 — 016 их не пересоздаёт."""
    sql = DDL_PATH.read_text(encoding="utf-8")
    created = set(re.findall(r"CREATE TABLE IF NOT EXISTS catalog\.(\w+)", sql))
    assert "curriculum_plan" not in created
    assert "curriculum_plan_row" not in created


def test_ddl_uses_identity_pk() -> None:
    # Working-таблицы пишутся в рантайме → PK через IDENTITY.
    assert "GENERATED BY DEFAULT AS IDENTITY" in DDL_PATH.read_text(encoding="utf-8")


def test_functions_file_defines_compat_functions() -> None:
    sql = FUNCTIONS_PATH.read_text(encoding="utf-8")
    assert "CREATE OR REPLACE FUNCTION catalog.search_norm(value text)" in sql
    assert "CREATE OR REPLACE FUNCTION catalog.json_valid(value text)" in sql
    assert "CREATE OR REPLACE FUNCTION catalog.json_extract(value text, path text)" in sql
    # search_norm: lower ДО replace (иначе капитал Ё не нормализуется).
    assert "replace(lower(value), 'ё', 'е')" in sql


def test_ddl_statement_split_matches_created_tables() -> None:
    """Сплиттер как в alembic 014/016 не рвёт dollar-quoted функцию."""
    module = _load_module(MIG_PATH, "mig016")
    statements = module._statements()
    creates = [s for s in statements if s.lstrip().upper().startswith("CREATE TABLE")]
    assert len(creates) == len(EXPECTED_CREATED)


def test_alembic_016_revision_chain() -> None:
    module = _load_module(MIG_PATH, "mig016_rev")
    assert module.revision == "016"
    assert module.down_revision == "015"
    assert set(module._WORKING_TABLES) == EXPECTED_CREATED


def test_migrate_script_table_order_is_fk_safe() -> None:
    module = _load_module(MIGRATE_SCRIPT, "migrate_catalog")
    working = module.WORKING_TABLES
    assert module.TABLES == module.CANONICAL_TABLES + working

    def before(parent: str, child: str) -> bool:
        return working.index(parent) < working.index(child)

    assert before("profile_brief", "evidence_source")
    assert before("skill_suggestion", "skill_prerequisite")
    assert before("curriculum_plan", "curriculum_plan_row")
    assert before("curriculum_plan_row", "skill_set_item")
    assert before("curriculum_artifact_template", "curriculum_artifact_template_scope")
    assert before("skill_set", "skill_set_item")


def test_migrate_script_covers_all_working_tables() -> None:
    module = _load_module(MIGRATE_SCRIPT, "migrate_catalog2")
    # 13 таблиц из 016 + curriculum_plan/row (015) + skill_group/indicator (017 admin-runtime).
    assert set(module.WORKING_TABLES) == EXPECTED_CREATED | {
        "curriculum_plan", "curriculum_plan_row", "skill_group", "indicator",
    }
