-- PostgreSQL DDL for the catalog-admin runtime tables (schema `catalog`).
-- Translated from ensure_catalog_admin_runtime_schema (viewer/app.py) for the full-PG cutover.
-- Applied by migrations/versions/017_catalog_admin_runtime_tables.py.
--
-- skill_group and indicator were built lazily by open_db() on SQLite and were missed by the
-- 014/015/016 cutover. skill.group_id is a soft integer reference (no FK) — skill_group lives
-- here as a standalone table. Their data is copied by scripts/migrate_catalog_to_postgres.py.
-- The skill admin columns (group_id, code, is_active, sort_order, …) already exist from 014.

CREATE TABLE IF NOT EXISTS catalog.skill_group (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       text NOT NULL UNIQUE,
    name       text NOT NULL UNIQUE,
    sort_order integer NOT NULL DEFAULT 999,
    status     text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'candidate', 'deprecated')),
    source     text NOT NULL DEFAULT 'derived' CHECK (source IN ('live_snapshot', 'manual', 'derived')),
    created_at text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at text
);

CREATE TABLE IF NOT EXISTS catalog.indicator (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id                integer NOT NULL REFERENCES catalog.skill(id) ON DELETE CASCADE,
    indicator_type          text NOT NULL,
    text                    text NOT NULL,
    normalized_text         text NOT NULL,
    sort_order              integer NOT NULL DEFAULT 999,
    complexity_band         text,
    complexity_label        text,
    complexity_sort_order   integer,
    source_indicator_row_id integer,
    source_profile_name     text,
    source_scale_title      text,
    is_active               integer NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at              text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at              text,
    UNIQUE (skill_id, indicator_type, normalized_text)
);

CREATE INDEX IF NOT EXISTS idx_indicator_skill_active
    ON catalog.indicator(skill_id, is_active, sort_order);

-- skill-admin management indexes (skill columns already exist from migration 014).
CREATE INDEX IF NOT EXISTS idx_skill_group_id
    ON catalog.skill(group_id, is_active, sort_order, name);
CREATE INDEX IF NOT EXISTS idx_skill_code ON catalog.skill(code);
CREATE INDEX IF NOT EXISTS idx_skill_active_status ON catalog.skill(status, is_active);

-- Timestamp columns are NOT NULL DEFAULT CURRENT_TIMESTAMP on SQLite; the 014/015 PG translation
-- dropped the default, so runtime inserts that omit them hit a NOT NULL violation. Restore the
-- default with the same text shape SQLite produces ('YYYY-MM-DD HH24:MI:SS').
ALTER TABLE catalog.ai_analysis_run   ALTER COLUMN started_at SET DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS');
ALTER TABLE catalog.ingest_run        ALTER COLUMN started_at SET DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS');
ALTER TABLE catalog.project           ALTER COLUMN created_at SET DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS');
ALTER TABLE catalog.project_indicator ALTER COLUMN created_at SET DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS');
ALTER TABLE catalog.review_queue      ALTER COLUMN created_at SET DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS');
ALTER TABLE catalog.curriculum_plan   ALTER COLUMN created_at SET DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS');
ALTER TABLE catalog.curriculum_plan   ALTER COLUMN updated_at SET DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS');

-- prerequisite_edge_decision.src/dst_suggestion_id are SOFT references parsed from the visual edge
-- label ('S1->S2') and may point at suggestions that were superseded or never created (SQLite ran
-- with FK enforcement off). Drop the FK enforcement to match that behavior; keep the brief_id FK.
ALTER TABLE catalog.prerequisite_edge_decision DROP CONSTRAINT IF EXISTS prerequisite_edge_decision_src_suggestion_id_fkey;
ALTER TABLE catalog.prerequisite_edge_decision DROP CONSTRAINT IF EXISTS prerequisite_edge_decision_dst_suggestion_id_fkey;
