-- PostgreSQL DDL for the catalog working/intake tables (schema `catalog`).
-- Translated from new_tables.sql (SQLite) for the full-PG cutover (Phase-4c).
-- Applied by migrations/versions/016_catalog_working_tables.py.
--
-- Working tables are written at runtime, so their PK uses IDENTITY (migration inserts
-- explicit ids; runtime gets auto ids — reset the identity after bulk load). curriculum_plan
-- and curriculum_plan_row are already created by migration 015 and are NOT redefined here.

-- Compatibility functions (search_norm/json_valid/json_extract) live in
-- catalog_functions_postgres.sql, applied by the same migration.

CREATE TABLE IF NOT EXISTS catalog.profile_brief (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_text      text NOT NULL,
    role          text,
    seniority     text,
    domain        text,
    created_at    text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    metadata_json text
);

CREATE TABLE IF NOT EXISTS catalog.evidence_source (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brief_id      integer REFERENCES catalog.profile_brief(id) ON DELETE CASCADE,
    claim         text NOT NULL,
    source_type   text NOT NULL CHECK (source_type IN ('vacancy', 'framework', 'syllabus', 'other')),
    url           text,
    snippet       text,
    retrieved_at  text NOT NULL
);

CREATE TABLE IF NOT EXISTS catalog.evidence_query_cache (
    cache_key text PRIMARY KEY,
    normalized_query text NOT NULL,
    query text NOT NULL,
    model text NOT NULL,
    response_json text NOT NULL,
    created_at text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_evidence_query_cache_updated
    ON catalog.evidence_query_cache(updated_at);

CREATE TABLE IF NOT EXISTS catalog.skill_suggestion (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brief_id      integer REFERENCES catalog.profile_brief(id) ON DELETE CASCADE,
    suggested_name text NOT NULL,
    source_name   text,
    group_name    text,
    coverage_area text,
    bloom         text,
    indicators_json text,
    tools         text,
    resolution    text CHECK (resolution IN ('matched', 'alias', 'fuzzy', 'new')),
    canonical_skill_id integer REFERENCES catalog.skill(id) ON DELETE SET NULL,
    match_score   double precision,
    nearest_skill_id integer REFERENCES catalog.skill(id) ON DELETE SET NULL,
    nearest_name  text,
    nearest_group text,
    confidence    double precision,
    council_agreement double precision,
    evidence_ids  text,
    decision      text NOT NULL DEFAULT 'pending' CHECK (decision IN ('pending', 'accepted', 'needs_review', 'rejected', 'superseded')),
    entity_type   text NOT NULL DEFAULT 'skill',
    atomicity     text NOT NULL DEFAULT 'unknown',
    parent_suggestion_id integer REFERENCES catalog.skill_suggestion(id) ON DELETE SET NULL,
    atomize_rationale text
);

CREATE TABLE IF NOT EXISTS catalog.skill_prerequisite (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brief_id      integer REFERENCES catalog.profile_brief(id) ON DELETE CASCADE,
    src_skill_id  integer REFERENCES catalog.skill(id) ON DELETE CASCADE,
    dst_skill_id  integer REFERENCES catalog.skill(id) ON DELETE CASCADE,
    src_suggestion_id integer REFERENCES catalog.skill_suggestion(id) ON DELETE SET NULL,
    dst_suggestion_id integer REFERENCES catalog.skill_suggestion(id) ON DELETE SET NULL,
    src_name      text NOT NULL,
    dst_name      text NOT NULL,
    relation_type text NOT NULL DEFAULT 'hard' CHECK (relation_type IN ('hard', 'soft')),
    confidence    double precision,
    source        text,
    review_state  text NOT NULL DEFAULT 'needs_review' CHECK (review_state IN ('accepted', 'needs_review', 'draft'))
);

CREATE TABLE IF NOT EXISTS catalog.prerequisite_edge_decision (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brief_id      integer NOT NULL REFERENCES catalog.profile_brief(id) ON DELETE CASCADE,
    edge_key      text NOT NULL,
    src_suggestion_id integer REFERENCES catalog.skill_suggestion(id) ON DELETE SET NULL,
    dst_suggestion_id integer REFERENCES catalog.skill_suggestion(id) ON DELETE SET NULL,
    relation_type text NOT NULL DEFAULT 'soft' CHECK (relation_type IN ('hard', 'soft')),
    confidence    double precision,
    source        text,
    decision      text NOT NULL CHECK (decision IN ('accepted', 'rejected')),
    resolution_note text,
    created_at    text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at    text,
    UNIQUE (brief_id, edge_key)
);

CREATE INDEX IF NOT EXISTS idx_prerequisite_edge_decision_brief
    ON catalog.prerequisite_edge_decision(brief_id, decision);

CREATE TABLE IF NOT EXISTS catalog.intake_job (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_kind   text NOT NULL CHECK (source_kind IN ('text', 'file')),
    source_name   text,
    file_path     text,
    brief_text    text NOT NULL,
    status        text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'succeeded', 'failed')),
    current_stage text,
    progress_note text,
    error_text    text,
    result_payload text,
    use_council   integer NOT NULL DEFAULT 1,
    created_at    text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at    text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    started_at    text,
    finished_at   text,
    brief_id      integer REFERENCES catalog.profile_brief(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_intake_job_created ON catalog.intake_job(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_intake_job_status ON catalog.intake_job(status, created_at DESC);

CREATE TABLE IF NOT EXISTS catalog.curriculum_artifact_template (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          text NOT NULL UNIQUE,
    title         text NOT NULL,
    artifact_family text NOT NULL CHECK (
        artifact_family IN ('analysis', 'document', 'configuration', 'design', 'production', 'practice')
    ),
    artifact_description text NOT NULL,
    project_name_pattern text,
    materials_pattern text,
    storytelling_pattern text,
    validation_criteria text,
    priority      integer NOT NULL DEFAULT 100,
    status        text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'draft', 'deprecated')),
    source        text NOT NULL DEFAULT 'manual',
    created_at    text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at    text
);

CREATE TABLE IF NOT EXISTS catalog.curriculum_artifact_template_scope (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id   integer NOT NULL REFERENCES catalog.curriculum_artifact_template(id) ON DELETE CASCADE,
    scope_type    text NOT NULL CHECK (scope_type IN ('taxonomy_node', 'skill_group', 'coverage_area', 'any')),
    scope_id      integer,
    scope_name    text,
    normalized_scope_name text,
    weight        double precision NOT NULL DEFAULT 1.0,
    created_at    text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE (template_id, scope_type, scope_id, normalized_scope_name)
);

CREATE INDEX IF NOT EXISTS idx_curriculum_artifact_template_status
    ON catalog.curriculum_artifact_template(status, artifact_family, priority);

CREATE INDEX IF NOT EXISTS idx_curriculum_artifact_template_scope
    ON catalog.curriculum_artifact_template_scope(scope_type, normalized_scope_name);

CREATE TABLE IF NOT EXISTS catalog.skill_set (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          text NOT NULL UNIQUE,
    title         text NOT NULL,
    description   text,
    source_type   text NOT NULL CHECK (source_type IN ('brief', 'curriculum_plan', 'manual', 'system')),
    source_id     integer,
    source_ref    text,
    status        text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'draft', 'archived')),
    metadata_json text NOT NULL DEFAULT '{}',
    created_at    text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at    text
);

CREATE TABLE IF NOT EXISTS catalog.skill_set_item (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_set_id  integer NOT NULL REFERENCES catalog.skill_set(id) ON DELETE CASCADE,
    skill_id      integer NOT NULL REFERENCES catalog.skill(id) ON DELETE CASCADE,
    suggestion_id integer REFERENCES catalog.skill_suggestion(id) ON DELETE SET NULL,
    plan_row_id   integer REFERENCES catalog.curriculum_plan_row(id) ON DELETE SET NULL,
    role          text NOT NULL DEFAULT 'target' CHECK (role IN ('target', 'prerequisite', 'reinforcement', 'assessment')),
    weight        double precision NOT NULL DEFAULT 1.0,
    sort_order    integer NOT NULL DEFAULT 0,
    rationale     text,
    created_at    text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_skill_set_source
    ON catalog.skill_set(source_type, source_id, status);

CREATE INDEX IF NOT EXISTS idx_skill_set_item_set
    ON catalog.skill_set_item(skill_set_id, sort_order, id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_skill_set_item_unique
    ON catalog.skill_set_item(skill_set_id, skill_id, role, COALESCE(plan_row_id, 0));

CREATE INDEX IF NOT EXISTS idx_skill_set_item_skill
    ON catalog.skill_set_item(skill_id, role);

CREATE TABLE IF NOT EXISTS catalog.curriculum_artifact_template_proposal (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brief_id      integer NOT NULL REFERENCES catalog.profile_brief(id) ON DELETE CASCADE,
    plan_id       integer REFERENCES catalog.curriculum_plan(id) ON DELETE SET NULL,
    status        text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'accepted', 'rejected')),
    code          text NOT NULL,
    title         text NOT NULL,
    artifact_family text NOT NULL CHECK (
        artifact_family IN ('analysis', 'document', 'configuration', 'design', 'production', 'practice')
    ),
    scope_type    text NOT NULL DEFAULT 'coverage_area' CHECK (
        scope_type IN ('taxonomy_node', 'skill_group', 'coverage_area', 'any')
    ),
    scope_names_json text NOT NULL DEFAULT '[]',
    artifact_description text NOT NULL,
    project_name_pattern text,
    materials_pattern text,
    storytelling_pattern text,
    validation_criteria text,
    covered_skill_ids_json text NOT NULL DEFAULT '[]',
    covered_skill_names_json text NOT NULL DEFAULT '[]',
    rationale     text,
    confidence    double precision NOT NULL DEFAULT 0.75,
    source        text NOT NULL DEFAULT 'deterministic_proposer',
    accepted_template_id integer REFERENCES catalog.curriculum_artifact_template(id) ON DELETE SET NULL,
    created_at    text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at    text,
    UNIQUE (brief_id, code)
);

CREATE INDEX IF NOT EXISTS idx_curriculum_artifact_template_proposal_brief
    ON catalog.curriculum_artifact_template_proposal(brief_id, status, id);

CREATE TABLE IF NOT EXISTS catalog.skill_promotion_log (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suggestion_id integer NOT NULL UNIQUE REFERENCES catalog.skill_suggestion(id) ON DELETE CASCADE,
    skill_id      integer NOT NULL REFERENCES catalog.skill(id) ON DELETE CASCADE,
    alias         text NOT NULL,
    normalized_alias text NOT NULL,
    resolution_after_promotion text,
    created_skill integer NOT NULL DEFAULT 0 CHECK (created_skill IN (0, 1)),
    created_alias integer NOT NULL DEFAULT 0 CHECK (created_alias IN (0, 1)),
    status        text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'reverted')),
    source        text NOT NULL DEFAULT 'intake_accept',
    created_at    text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    reverted_at   text
);

CREATE INDEX IF NOT EXISTS idx_skill_promotion_log_skill
    ON catalog.skill_promotion_log(skill_id, status);
