"""catalog-admin runtime tables + IDENTITY on all runtime-written catalog tables

Two gaps in the SQLite→PG cutover (which only ever verified the read paths):

1. ``skill_group`` and ``indicator`` were built lazily by ``open_db()`` on SQLite
   (``ensure_catalog_admin_runtime_schema``) and never made it into Postgres.
2. The canonical tables (014) and ``curriculum_plan``/``curriculum_plan_row`` (015) were created
   with a plain ``integer PRIMARY KEY`` (rows migrated with explicit ids). But the catalog write
   paths — ingest and catalog-admin — ``INSERT`` without an id and rely on autoincrement. On
   Postgres every such write failed with a NOT NULL id violation. Promote every catalog table
   that has an ``id`` column to ``GENERATED BY DEFAULT AS IDENTITY`` and restart its identity to
   ``MAX(id)+1`` so runtime inserts never collide with migrated ids.

Data for skill_group/indicator (119 + 1566 rows) is copied by
``scripts/migrate_catalog_to_postgres.py``. The skill admin columns already exist (014).

Revision ID: 017
Revises: 016
"""

from pathlib import Path

from alembic import op

revision = "017"
down_revision = "016"
branch_labels = None
depends_on = None

_SCHEMA = "catalog"
_DDL_PATH = (
    Path(__file__).resolve().parents[2]
    / "src"
    / "content_factory"
    / "catalog"
    / "sql"
    / "admin_runtime_tables_postgres.sql"
)

# New tables created by this migration (already IDENTITY in the DDL — excluded from promotion).
_NEW_TABLES = ["indicator", "skill_group"]
_NEW_INDEXES = ["idx_skill_group_id", "idx_skill_code", "idx_skill_active_status"]


def _statements() -> list[str]:
    raw = _DDL_PATH.read_text(encoding="utf-8")
    stmts: list[str] = []
    for chunk in raw.split(";\n"):
        lines = [ln for ln in chunk.splitlines() if ln.strip() and not ln.strip().startswith("--")]
        if lines:
            stmts.append("\n".join(lines))
    return stmts


def _plain_id_tables(bind) -> list[str]:
    """Catalog tables that have a non-identity ``id`` column (need IDENTITY for runtime inserts)."""
    from sqlalchemy import text

    rows = bind.execute(
        text(
            "SELECT c.table_name FROM information_schema.columns c "
            "JOIN information_schema.tables t "
            "  ON t.table_schema = c.table_schema AND t.table_name = c.table_name "
            "WHERE c.table_schema = :s AND c.column_name = 'id' AND c.is_identity = 'NO' "
            "  AND t.table_type = 'BASE TABLE' "
            "ORDER BY c.table_name"
        ),
        {"s": _SCHEMA},
    ).fetchall()
    return [r[0] for r in rows]


def upgrade() -> None:
    for stmt in _statements():
        op.execute(stmt)

    # Promote every runtime-written catalog table's id to IDENTITY and align the sequence with
    # any already-migrated explicit ids (MAX(id)+1). On a fresh DB tables are empty → starts at 1.
    from sqlalchemy import text

    bind = op.get_bind()
    for table in _plain_id_tables(bind):
        op.execute(f'ALTER TABLE {_SCHEMA}."{table}" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY')
        next_id = bind.execute(
            text(f'SELECT COALESCE(MAX(id), 0) + 1 FROM {_SCHEMA}."{table}"')
        ).scalar()
        op.execute(f'ALTER TABLE {_SCHEMA}."{table}" ALTER COLUMN id RESTART WITH {int(next_id)}')


def downgrade() -> None:
    from sqlalchemy import text

    bind = op.get_bind()
    # Drop IDENTITY from every catalog id column that has it, except the tables we drop below.
    rows = bind.execute(
        text(
            "SELECT table_name FROM information_schema.columns "
            "WHERE table_schema = :s AND column_name = 'id' AND is_identity = 'YES'"
        ),
        {"s": _SCHEMA},
    ).fetchall()
    for (table,) in rows:
        if table in _NEW_TABLES:
            continue
        op.execute(f'ALTER TABLE {_SCHEMA}."{table}" ALTER COLUMN id DROP IDENTITY IF EXISTS')
    for index in _NEW_INDEXES:
        op.execute(f"DROP INDEX IF EXISTS {_SCHEMA}.{index}")
    for table in _NEW_TABLES:
        op.execute(f"DROP TABLE IF EXISTS {_SCHEMA}.{table} CASCADE")
