"""persist immutable template snapshots for curriculum plan rows

Each generated UP row now records the exact brief-scoped or global template
revision used to build it.  The snapshot survives later template edits and
deletions, which makes plan versions reproducible without adding provenance
fields to the standard UP document.

Revision ID: 021_template_snapshot
Revises: 020_template_scope
"""

from alembic import op

revision = "021_template_snapshot"
down_revision = "020_template_scope"
branch_labels = None
depends_on = None

_SCHEMA = "catalog"


def upgrade() -> None:
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_SCHEMA}.curriculum_plan_row_template_binding (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            plan_row_id integer NOT NULL UNIQUE
                REFERENCES {_SCHEMA}.curriculum_plan_row(id) ON DELETE CASCADE,
            brief_id integer NOT NULL
                REFERENCES {_SCHEMA}.profile_brief(id) ON DELETE CASCADE,
            proposal_id integer
                REFERENCES {_SCHEMA}.curriculum_artifact_template_proposal(id) ON DELETE SET NULL,
            template_id integer
                REFERENCES {_SCHEMA}.curriculum_artifact_template(id) ON DELETE SET NULL,
            template_code text NOT NULL,
            template_version text NOT NULL DEFAULT '',
            source text NOT NULL CHECK (source IN ('brief', 'global')),
            repeatable boolean NOT NULL DEFAULT false,
            snapshot_json text NOT NULL,
            snapshot_sha256 text NOT NULL CHECK (length(snapshot_sha256) = 64),
            created_at text NOT NULL DEFAULT
                to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
        )
        """
    )
    op.execute(
        f"""
        CREATE INDEX IF NOT EXISTS idx_curriculum_row_template_binding_brief
        ON {_SCHEMA}.curriculum_plan_row_template_binding(brief_id, source, template_code)
        """
    )


def downgrade() -> None:
    op.execute(f"DROP TABLE IF EXISTS {_SCHEMA}.curriculum_plan_row_template_binding")
